### PR TITLE
Development

### PR DESCRIPTION
**Pull request by abelboldu**

### CODE REVIEW

**Comment by dguerri** [comment]
Wow.
Please update also the README.md to include RedHat distros! (Tested on Ubuntu Precise (12.04) and Trusty (14.04) I know we forgot that for other roles)

**Comment by abelboldu** [comment]
I only did some small deployment tests, so I am already adding them to metadata, but I want to change that when it's fully tested on Redhat and Centos (and with Kilo OSt release if it's possible).

**Comment by dguerri** [comment]
oh, ok. Let me try it on my test-bed.

**Comment by dguerri** [comment]
+2

**Comment by dguerri** [comment]
oops :)

**Pull request merged**
